// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp02cuMOHcYnMf2O-DDBgK22aIzVq4-Pk',
    appId: '1:501485604256:android:ea9e36c058e0f7d90d28c5',
    messagingSenderId: '501485604256',
    projectId: 'newbook-f6145',
    storageBucket: 'newbook-f6145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv9uGMGj5Lsh5UGi6yFjUy0GM2VOfzM2w',
    appId: '1:501485604256:ios:57db5ad3cc78aea10d28c5',
    messagingSenderId: '501485604256',
    projectId: 'newbook-f6145',
    storageBucket: 'newbook-f6145.appspot.com',
    iosClientId: '501485604256-9gq2tr2jl3949u3gh2ephqa6pcatjd6f.apps.googleusercontent.com',
    iosBundleId: '.app',
  );
}
